name: 'dbt_expectations_integration_tests'
version: '1.0'

profile: 'integration_tests'

config-version: 2

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

require-dbt-version: ">=0.18.1"

vars:
    'dbt_date:time_zone': 'AUS Eastern Standard Time'
    dbt_utils_dispatch_list: [tsql_utils]
    dbt_date_dispatch_list: [dbt_date_tsql]
    dbt_expectations_dispatch_list: [dbt_expectations_tsql]

quoting:
    database: true
    identifier: true
    schema: true

models:
    schema: dbt_date_integration_tests
    materialized: table